### ISSUE TITLE
Angular 9 - Very simple quick fixes.

### ISSUE THREAD

**Issue by TheDevelolper** [ng-bootstrap/schematics#11]
When installing using Angular 9 I needed to remove the: 

for.root() on NgbModule in the app.module. 

so it looks like this: 
``` typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  // imports: [BrowserModule, AppRoutingModule, NgbModule.forRoot()], <-- removed forRoot()
  imports: [BrowserModule, AppRoutingModule, NgbModule], //<-- should look like this.
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

I also needed to run: 
```bash
$ ng add @angular/localize
````
After that the project seemed to run just fine. 

I wanted to raise this workaround as an issue until the fixes are implemented to help anyone else having issues in getting this working.

**Comment by maxokorokov** [comment]
@ISimplifyComplexity thanks for the suggestion. 
This will be fixed in `6.1.0` of `@ng-bootstrap/ng-bootstrap` as schematics migrate there.
