### ISSUE TITLE
Import bootstrap SCSS file instead of CSS

### ISSUE THREAD

**Issue by bastienmoulia** [ng-bootstrap/schematics#2]
When the style is defined as `scss` in the angular.json file, it could be nice to import the scss file of bootstrap in style.scss instead of adding an input with the css file.

**Comment by pkozlowski-opensource** [comment]
I guess this should be a command line option. More generally I would love to see a separate Bootstrap schematic on which we could build...

**Comment by batousik** [comment]
Any updates?

**Comment by maxokorokov** [comment]
This will be fixed in `6.1.0` of `@ng-bootstrap/ng-bootstrap` as schematics migrate there and will be accessible view `ng add @ng-bootstrap/ng-bootstrap`
