### ISSUE TITLE
Feature Request: Query npm to get the latest version of ng-bootstrap

### ISSUE THREAD

**Issue by brijmcq** [ng-bootstrap/schematics#8]
I just recently found out that you can use the command ` ng add @ng-bootstrap/schematics` but it is installing an outdated version of ng-bootstrap ( ^2.0.0-alpha.1 ) . I'm just wondering if you still have plans on implementing this feature because I saw this in the source code https://github.com/ng-bootstrap/schematics/blob/master/src/ng-add/index.ts#L8 . If you think this is worth pursuing, maybe I can create a PR for this :)

**Comment by maxokorokov** [comment]
@brijmcq thanks for the suggestion. 
This will be fixed in `6.1.0` of `@ng-bootstrap/ng-bootstrap` as schematics migrate there and will be accessible via `ng add @ng-bootstrap/ng-bootstrap`
