### ISSUE TITLE
@ng-bootstrap/schematics does not work with angular workspace projects

### ISSUE THREAD

**Issue by realharry** [ng-bootstrap/schematics#9]
### Bug description:

1. Create an Angular workspace project which includes one or more app and/or library projects under the "projects" folder.
1. Try `ng add @ng-bootstrap/schematics`.

You get an error
```
Could not find file for path: src/app/app.module.ts
```

### Link to minimally-working StackBlitz that reproduces the issue:

N/A

### Versions of Angular, ng-bootstrap and Bootstrap:

* @ng-bootstrap/schematics: 2.0.0-alpha.1
* ng-bootstrap: 6.0.0
* Angular: 9.0.5
* Bootstrap: 4.4.1

**Comment by benouat** [comment]
Seems to be a duplicate of #6

**Comment by realharry** [comment]
Hi @benouat Good morning!

It's not really a big issue since one can easily add ng-bootstrap dependency manually. It will be very useful though, especially for new users, to be able to use schematics to generate boilerplate pages, etc. (as Angular Material does, for instance). Just a thought!

I'll close this ticket as duplicate. Thanks!
